//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class accomplish
    {
        public int accomplishId { get; set; }
        public int accomplishStudent { get; set; }
        public int accomplishTask { get; set; }
        public Nullable<bool> isAccomplish { get; set; }
    
        public virtual student student { get; set; }
        public virtual task task { get; set; }
    }
}
