//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class COURSESEntities : DbContext
    {
        public COURSESEntities()//"data source=DESKTOP-49VMUKQ;initial catalog=COURSES;integrated security=True;MultipleActiveResultSets=True"
            : base(" name = COURSESEntities")//name=COURSESEntities
        {/* המורה אמרה להוסיף את זה בשביל החיבור */
            base.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accomplish> accomplishes { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<studentCourse> studentCourses { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<task> tasks { get; set; }
    }
}
